// layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Toaster } from "react-hot-toast";

import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { Provider } from "@/extra/provider";

const inter = Inter({ subsets: ["latin"] });
const clientId = process.env.NEXT_PUBLIC_CLIENT_ID as string;


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
  
      <html lang="en">
        <body className={inter.className}>
       <Provider>
          <GoogleOAuthProvider clientId={clientId}>

            {children}
       
            <Toaster />
            <ReactQueryDevtools />
          </GoogleOAuthProvider>
          </Provider>
        </body>
      </html>
   
  );
}
